- cmd/mqtt2prometheus.go
- config.yaml.dist
- pkg/config/config.go
- pkg/metrics/ingest.go
- Added MQTT username / password configuration options.
- Fixed blocking error channel 
- JSON Payload value types are no longer required to be numbers. Once mapped to a metric type the value will be checked before storing the metric.
> MQTT auth, fixed error handling, less strict json parsing

- cmd/mqtt2prometheus.go
- pkg/config/config.go
Hi,
there was a problem that the cache always lasted 2 minutes, regardless of the setting in the config file. The reason was a bug in the config.go and a bug in the mqtt2prometheus.go. With the fix the "timeout" value from the config file is now reflected in the behavior of the exporter.
> fixed wrong cache behavior (was always 2 minutes)

- config.yaml.dist
- pkg/config/config.go
- pkg/metrics/ingest.go
Various sensors have string attributes such as "state" which are still
useful to track as metrics. For example, state may be "on" or "off".
These can be showen as 1 and 0 and be used to trigger alerts.
> Parse more value types

- cmd/mqtt2prometheus.go
- config.yaml.dist
- pkg/config/config.go
- pkg/metrics/ingest.go
Adds a new config option `sensor_name_filter` which is a regular expression. This is useful for when different types of sensors present different metrics under the same metric name.
> Sensor name filtering

- Readme.md
- cmd/mqtt2prometheus.go
- config.yaml.dist
- examples/gosund_sp111.yaml
- go.mod
- go.sum
- pkg/config/config.go
- pkg/metrics/collector.go
- pkg/metrics/ingest.go
This PR add support for tasmota based devices. I test it with the Gosund SP111 device. 
There are two major changes in this PR:
1. The device ID can be specified by an regex. This regex is applied to the topic path. Thus the device ID can be located everywhere in the topic path.
2. Since tasmota produces nested json object payloads, the json name of the metric will be converted to an [gojsonq path](https://github.com/thedevsaddam/gojsonq/wiki/Queries#findpath). 
This PR should not change any old configuration. Thus it will be downward compatible.
Checklist:
> Support tasmota

- hack/docker-compose.yml
- hack/prometheus.yml
As mqtt2promethius is built from source,
it should export 9641:9641 instead of 8002:8002
Fixes issue #17
> Changed incorrect port number

- pkg/config/config.go
When sending a topic that doesn't match the configured regex, `mqtt2prometheus` currently just crashes.
This can be reproduced by using this config and then publishing a message to `shellies/test`:
```yaml
mqtt:
server: tcp://mosquitto:1883
topic_path: shellies/#
device_id_regex: "shellies/(?P<deviceid>.*)/sensor"
metric_per_topic_config:
metric_name_regex: "shellies/(?P<deviceid>.*)/sensor/(?P<metricname>.*)"
```
This patch ignores topic not parseable by the regex instead and outputs the following error instead:
```
error        cmd/mqtt2prometheus.go:119        Error while processing message
{"error": "could not store metrics '' on topic shellies/test: failed to extract metric values from topic: failed to find valid metric in topic path"}
```
> Make GroupValue() more resilient

- pkg/config/config.go
This uses `StrictUnmarshal()` when parsing the config, which should make it fail when unknown config attributes are used.
This would've helped me spot https://github.com/hikhvar/mqtt2prometheus/issues/52, so I thought it might be worth a consideration.
Here's the error displayed with an invalid YAML:
```
fatal   cmd/mqtt2prometheus.go:72       Could not load config   {"error": "yaml: unmarshal errors:\n  line 8: field cache not found in type config.MQTTConfig"}
```
I've tested this with the other example configs, but not sure if there might be a side effect I'm not catching here.
> Use UnmarshalStrict for config file to catch config errors

- go.mod
- go.sum
Testing out bumping the mqtt dependency to try and fix #60
> Bumping mqtt dependency

- Readme.md
- cmd/mqtt2prometheus.go
This PR adds the ability to provide a username and password for the MQTT broker via the environment instead of the configuration file.
If the environment variables `MQTT2PROM_MQTT_USER` and `MQTT2PROM_MQTT_PASSWORD` exist and are not empty, they will override those parameters in the configuration file.
This is especially helpful when trying to avoid leaking application secrets via a version control system.
> Enable providing mqtt login details via the environment

- release/Dockerfile.scratch
This brings it in line with the root `Dockerfile` and helps avoid having to repeat the name of the binary when adding command line args.
> Use ENTRYPOINT to allow command line argument customization

- freebsd/mqtt2prometheus.rc
I’m using the exporter on a FreeBSD box via the existing pkg/port but I noticed there is no rc script included. So I wrote this super basic one that’s been working well for me. 
I might have some time at some point to make it more configurable, but wanted to share the current version in case it’s helpful for someone else. And it can also easily be integrated in the pkg/port. 
Let me know if you’d rather have the more advanced version and I’ll see if I can make some time to update it.
> FreeBSD rc script

- Readme.md
- pkg/config/config.go
- pkg/metrics/parser.go
- pkg/metrics/parser_test.go
optional `mqtt_value_scale` defines a scale for conversion; example use case: convert percentage into 0.0-1.0 value range
> Scaling option for values

- Readme.md
- pkg/config/config.go
- pkg/metrics/collector.go
- pkg/metrics/parser.go
- pkg/metrics/parser_test.go
In prometheus exposition format timestamps are not mandatory; here's my current setup:
- ESP32 is emitting external temp and hum to MQTT and then going into deep sleep for 15 minutes
- Omitting the timestamp let the scraping "to emit" a value on each scrape
I opted for `0` time value instead of playing with pointers and `nil`
> Option to omit timestamp

- Readme.md
- examples/shelly_3em.yaml
- pkg/config/config.go
This adds `object_per_topic_config` and `metric_per_topic_config` to the documentation as well as an example taken from https://github.com/hikhvar/mqtt2prometheus/issues/96. It also adds a check when parsing the config to make sure both are not specified.
> Adding documentation for object_per_topic_config and metric_per_topic_config

- pkg/metrics/extractor.go
- pkg/metrics/extractor_test.go
- pkg/metrics/parser.go
- pkg/metrics/parser_test.go
This commit reorganizes the logic in `parseMetric` to have it take in a `MetricConfig` so that the extractor can find the config and properly handle the case when there's no config found.
> Remove incorrect errors when using SensorNameFilter

- Readme.md
- cmd/mqtt2prometheus.go
This PR adds support for reading the password from a secret file. Usually if the base image has a shell, we can modify the entry point to a shell and create the environment variable, (e.g. `/bin/sh -c export MQTT2PROM_MQTT_PASSWORD=$$(cat /var/run/secrets/mqtt-credential); /mqtt2prometheus`) but with a distroless base image we don't have that option. 
Fixes #117
> add support for reading mqtt password from file

- .goreleaser.yml
- systemd/mqtt2prometheus
- systemd/mqtt2prometheus.service
- systemd/postinstall.sh
I tried installing mqtt2prometheus using the provided debian package, but I had a few issues with it:
- The environment file that is used in the systemd service, is not actually provided in the package. I fixed this by adding a default environment file and adjusting the goreleaser config accordingly
- I had some issues because the `mqtt2prometheus` user was not created correctly. However, it is also not really required to create a separate user for a service like this, so I added the `DynamicUser=true` option to the systemd service file. While at this, I also added some other security hardening options. The service runs fine with these options on my install (Ubuntu Server 22.04) and as far as I can tell it should run fine like this, but as always with security options, it can cause …
> Improve systemd unit file security and fix debian packaging

- pkg/metrics/instrumentation.go
This patch renames the ``received_messages`` metric to ``mqtt2prometheus_received_messages_total``, making it a bit more in line with conventional Prometheus metric naming.
I also slightly adjusted the descriptions.
> Rename received_messages metric to be more conventional

- Readme.md
JSON needs to be upper case, otherwiese "could not setup a metric extractor {"error": "unsupported object format: json"} " is thrown.
> Update Readme.md: object_per_topic_config: encoding need to be upper case

- Readme.md
- hack/shellyplusht.yaml
- pkg/config/config.go
- pkg/metrics/extractor.go
Hello
I try to use your exporter to scrap Shelly Plus H&T sensor metrics.
This device tends to use a metric per topic and sends some metrics in json format:
shellies/shellyplusht-xxx/status/humidity:0 {"id": 0,"rh":51.9}
shellies/shellyplusht-xxx/status/temperature:0 {"id": 0,"tC":22.4, "tF":72.3}
Thanks.
> Handle json payload in metric_per_topic mode

- cmd/mqtt2prometheus.go
- config.yaml.dist
- pkg/config/config.go
Added a new configuration `enable_profiling_metrics` which enable/disable the default runtime metrics exported by the Prometheus client package.
BREAKING CHANGE: Changed default behavior to exclude runtime metrics.
Enable with enable_profiling_metrics configuration option.
> feat: Add configuration option to enable/disable profiling metrics

- Readme.md
- cmd/mqtt2prometheus.go
- config.yaml.dist
- fuzzing/json_per_topic/fuzz.go
- fuzzing/metric_per_topic/fuzz.go
- hack/dht22.yaml
- pkg/config/config.go
- pkg/metrics/parser.go
- pkg/metrics/parser_test.go
in order to better handle errors in config metric:
- move `string_mapping_value.error_value` to upper level
- mark `string_mapping_value.error_value` as deprecated
if there's an error during type conversion or during execution of `expression` then `error_value` is returned (if set, otherwise an error is thrown and no metric is sent)
> make error_value global to metric and add error_expression

- pkg/metrics/parser.go
try to better handle string to int and string to float in expressions
> improve expr float() and int() to handle strings

- Readme.md
- pkg/config/config.go
- pkg/metrics/parser.go
- pkg/metrics/parser_test.go
add `raw_expression` in metric config in order to handle dynamic string MQTT values. It runs without type conversion while `expression`does.
here is a use case: a MQTT metric returned a string with the current datetime using the format H20241227104456 and it would be nice to be able to convert this to the corresponding unix time() to make it a prometheus valid value. Currently mqtt2prometheus is not able to handle this usecase.
With `raw_expression`, I would set the following:
```yaml
raw_expression: 'date(string(raw_value), "H060102150405", "Europe/Paris").Unix()'
```
Note: this PR must be merged after #157 and after #161
> add raw_expression
